#!/bin/bash

downloader()
{
    source=0
    input="website"
    save="link.txt"

    if [[ -z $1 ]]; then
        printf " ~> Target: "
        read target
    else
        target=$1
    fi

    if [[ ! -z $2 ]]; then
        save=$2
    fi

    printf "\n==> Downloading Website\n"
    wget $target -O website -q

    printf "==> Starting read of the website\n"
    printf " ~> Extracting\n"

    while IFS= read -r line
    do
        if [[ $line == *"href="* || $line == *"src="* ]]; then
            echo $line | grep -Eo 'src="[^\"]+"' | cut -d '"' -f 2  >> tmp
            echo $line | grep -Eo 'href="[^\"]+"' | cut -d '"' -f 2  >> tmp
            source=$((source + 1))
        fi
    done < "$input"
    printf " ~> Converting sources\n"
    while IFS= read -r line
    do
        if [[ $line == "/"* ]]; then
            echo $target$line >> $save
        else
            echo $line >> $save
        fi
    done < "tmp"
    printf "\n==> $source sources have been saved into $save\n"
    if [[ $source -lt 10 ]]; then
        printf "==> There is maybe a login page\n"
    fi
    rm website
    rm tmp
}

downloader $1 $2
